---
kind: pipeline
type: docker
name: deploy staging

steps:
  - name: deploy staging
    image: docker/compose:1.25.5
    environment:
      MONGO_INITDB_ROOT_USERNAME:
        from_secret: MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD:
        from_secret: MONGO_INITDB_ROOT_PASSWORD
      OPEN_DATA_USER:
        from_secret: OPEN_DATA_USER
      OPEN_DATA_KEY:
        from_secret: OLD_DATA_KEY
      MONGO_INITDB_DATABASE:
        from_secret: MONGO_INITDB_DATABASE
      MONGO_NON_ROOT_ROLE:
        from_secret: MONGO_NON_ROOT_ROLE
      MONGO_NON_ROOT_USERNAME:
        from_secret: MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD:
        from_secret: MONGO_NON_ROOT_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker-compose -f /drone/src/docker-compose.dev.yml up --detach --build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch: develop
  event: push
