version: "3.8"
services:
  library-mongodb:
    container_name: library-mongodb-dev
    volumes:
      - dev-mongodb-library:/data/db
    ports:
      - "127.0.0.1:27017:27017"

  library-scraper:
    container_name: library-scraper-dev
    environment:
      - DEV_RUN=true

volumes:
  dev-mongodb-library:
    external:
      name: dev-mongodb-library
