version: '3.7'
services:
  mongo-db:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./.docker/data/db:/data/db
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo-db
    restart: unless-stopped
#  mongo-express:
#    image: mongo-express
#    restart: unless-stopped
#    depends_on:
#      - mongo-db
#    ports:
#      - 8081:8081
#    env_file:
#      - .env
