version: '3.7'
services:

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    env_file:
      - .env
    expose:
      - 27017
    volumes:
      - dev-mongodb-library:/data/db
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo-db
    restart: unless-stopped

volumes:
  dev-mongodb-library:
    external:
      name: dev-mongodb-library
